// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Blacklist
{
    public Guid BlacklistId { get; set; }

    public Guid UserId { get; set; }

    public string Reason { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User User { get; set; }
}