// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class Contract
{
    [Key]
    public Guid ContractId { get; set; } = Guid.NewGuid();

    public Guid UserId { get; set; }

    public Guid VehicleId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Terms { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}