// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Deposit
{
    public Guid DepositId { get; set; }

    public Guid RentalId { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public virtual Rental Rental { get; set; }
}