// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class Feedback
{
    [Key]
    public Guid FeedbackId { get; set; } = Guid.NewGuid();

    public Guid UserId { get; set; }

    public Guid RentalId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Rental Rental { get; set; }

    public virtual User User { get; set; }
}