// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class IncidentReport
{
    public Guid ReportId { get; set; }

    public Guid? RentalId { get; set; }

    public Guid? VehicleId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? StaffId { get; set; }

    public string Description { get; set; }

    public DateTime? ReportDate { get; set; }

    public string Status { get; set; }

    public virtual Rental Rental { get; set; }

    public virtual User Staff { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}