// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class Payment
{
    [Key]
    public Guid PaymentId { get; set; } = Guid.NewGuid();

    public Guid RentalId { get; set; }

    public Guid UserId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    // Mã giao dịch từ PayOS để phục vụ xác thực
    [MaxLength(100)]
    public string TransactionId { get; set; }

    public virtual Rental Rental { get; set; }

    public virtual User User { get; set; }
}