// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Rental
{
    public Guid RentalId { get; set; }

    public Guid UserId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid PickupStationId { get; set; }

    public Guid? ReturnStationId { get; set; }

    public Guid? StaffId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string PickupNote { get; set; }

    public string PickupPhotoUrl { get; set; }

    public string ReturnNote { get; set; }

    public string ReturnPhotoUrl { get; set; }

    public decimal? TotalCost { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Deposit> Deposits { get; set; } = new List<Deposit>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Station PickupStation { get; set; }

    public virtual Station ReturnStation { get; set; }

    public virtual User Staff { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}