// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class RentalImage
{
    [Key]
    public Guid ImageId { get; set; } = Guid.NewGuid();

    public Guid RentalId { get; set; }

    public string ImageUrl { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Note { get; set; }

    public virtual Rental Rental { get; set; }
}