// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class Rental
{
    [Key]
    public Guid RentalId { get; set; } = Guid.NewGuid();

    public Guid? ContractId { get; set; }

    public Guid UserId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid PickupStationId { get; set; }

    public Guid? ReturnStationId { get; set; }

    public Guid? StaffId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal? TotalCost { get; set; }

    public string Status { get; set; } = "Pending";

    // --- Check-in (Delivery) metadata ---
    public DateTime? DeliveredAt { get; set; }
    public Guid? DeliveredByStaffId { get; set; }
    public string? DeliveryCondition { get; set; }

    // --- Check-out (Return) metadata ---
    public DateTime? ReceivedAt { get; set; }
    public Guid? ReceivedByStaffId { get; set; }
    public string? ReturnCondition { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<IncidentReport> IncidentReports { get; set; } = new List<IncidentReport>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Station PickupStation { get; set; }

    public virtual ICollection<RentalImage> RentalImages { get; set; } = new List<RentalImage>();

    public virtual Station ReturnStation { get; set; }

    public virtual User Staff { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}
