// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Reservation
{
    public Guid ReservationId { get; set; }

    public Guid UserId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid StationId { get; set; }

    public DateTime? ReservedAt { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Status { get; set; }

    public virtual Station Station { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}