// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Station
{
    public Guid StationId { get; set; }

    public string StationName { get; set; }

    public string Address { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual ICollection<Rental> RentalPickupStations { get; set; } = new List<Rental>();

    public virtual ICollection<Rental> RentalReturnStations { get; set; } = new List<Rental>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}