// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

public partial class SWP391RentEVContext : DbContext
{
    public SWP391RentEVContext()
    {
        
    }
    public SWP391RentEVContext(DbContextOptions<SWP391RentEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Blacklist> Blacklists { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<IncidentReport> IncidentReports { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Rental> Rentals { get; set; }

    public virtual DbSet<RentalImage> RentalImages { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserOtp> UserOtps { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blacklist>(entity =>
        {
            entity.HasKey(e => e.BlacklistId).HasName("PK__Blacklis__AFDBF4182C7461E8");

            entity.ToTable("Blacklist");

            entity.Property(e => e.BlacklistId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.BlacklistCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__Blacklist__Creat__3493CFA7");

            entity.HasOne(d => d.User).WithMany(p => p.BlacklistUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Blacklist__UserI__339FAB6E");
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("PK__Contract__C90D3469C4705457");

            entity.ToTable("Contract");

            entity.Property(e => e.ContractId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Active");
            entity.Property(e => e.Terms).HasMaxLength(1000);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(20, 2)");

            entity.HasOne(d => d.User).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract__UserId__5EBF139D");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract__Vehicl__5FB337D6");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Feedback__6A4BEDD6E580CFC0");

            entity.ToTable("Feedback");

            entity.Property(e => e.FeedbackId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.Comment).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Rental).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.RentalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedback__Rental__778AC167");

            entity.HasOne(d => d.User).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedback__UserId__76969D2E");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Incident__D5BD4805714850A8");

            entity.ToTable("IncidentReport");

            entity.Property(e => e.ReportId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ReportDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Open");

            entity.HasOne(d => d.Rental).WithMany(p => p.IncidentReports)
                .HasForeignKey(d => d.RentalId)
                .HasConstraintName("FK__IncidentR__Renta__2BFE89A6");

            entity.HasOne(d => d.Staff).WithMany(p => p.IncidentReportStaffs)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK__IncidentR__Staff__2EDAF651");

            entity.HasOne(d => d.User).WithMany(p => p.IncidentReportUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__IncidentR__UserI__2DE6D218");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.IncidentReports)
                .HasForeignKey(d => d.VehicleId)
                .HasConstraintName("FK__IncidentR__Vehic__2CF2ADDF");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A383F0D9C78");

            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.Amount).HasColumnType("decimal(20, 2)");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.Rental).WithMany(p => p.Payments)
                .HasForeignKey(d => d.RentalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__RentalI__6FE99F9F");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__UserId__70DDC3D8");
        });

        modelBuilder.Entity<Rental>(entity =>
        {
            entity.HasKey(e => e.RentalId).HasName("PK__Rental__97005943384E2FF7");

            entity.ToTable("Rental");

            entity.Property(e => e.RentalId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TotalCost).HasColumnType("decimal(20, 2)");

            entity.HasOne(d => d.Contract).WithMany(p => p.Rentals)
                .HasForeignKey(d => d.ContractId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Rental_Contract");

            entity.HasOne(d => d.PickupStation).WithMany(p => p.RentalPickupStations)
                .HasForeignKey(d => d.PickupStationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Rental__PickupSt__68487DD7");

            entity.HasOne(d => d.ReturnStation).WithMany(p => p.RentalReturnStations)
                .HasForeignKey(d => d.ReturnStationId)
                .HasConstraintName("FK__Rental__ReturnSt__693CA210");

            entity.HasOne(d => d.Staff).WithMany(p => p.RentalStaffs)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK__Rental__StaffId__6A30C649");

            entity.HasOne(d => d.User).WithMany(p => p.RentalUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Rental__UserId__66603565");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Rentals)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Rental__VehicleI__6754599E");
        });

        modelBuilder.Entity<RentalImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__RentalIm__7516F70C713896C0");

            entity.ToTable("RentalImage");

            entity.Property(e => e.ImageId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Rental).WithMany(p => p.RentalImages)
                .HasForeignKey(d => d.RentalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RentalIma__Renta__17F790F9");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.ReservationId).HasName("PK__Reservat__B7EE5F2483D8858D");

            entity.ToTable("Reservation");

            entity.Property(e => e.ReservationId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.ReservedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.Station).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__Stati__1F98B2C1");

            entity.HasOne(d => d.User).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__UserI__1DB06A4F");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__Vehic__1EA48E88");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1AF489698B");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId).HasName("PK__Station__E0D8A6BDE163D1A0");

            entity.ToTable("Station");

            entity.Property(e => e.StationId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4CC600D509");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__A9D10534C6163B8C").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DriverLicense).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IdentityCard).HasMaxLength(50);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__User__RoleId__4F7CD00D");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicle__476B54928E3106DE");

            entity.ToTable("Vehicle");

            entity.Property(e => e.VehicleId).HasDefaultValueSql("(UUID())");
            entity.Property(e => e.Description)
                .HasMaxLength(500);
            entity.Property(e => e.LicensePlate).HasMaxLength(20);
            entity.Property(e => e.PricePerDay).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Available");
            entity.Property(e => e.Utilities).HasMaxLength(200);
            entity.Property(e => e.VehicleName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.VehicleType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500);

            entity.HasOne(d => d.Station).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Vehicle__Station__59063A47");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}