// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PasswordHash { get; set; }

    public string IdentityCard { get; set; }

    public string DriverLicense { get; set; }

    public Guid RoleId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Rental> RentalStaffs { get; set; } = new List<Rental>();

    public virtual ICollection<Rental> RentalUsers { get; set; } = new List<Rental>();

    public virtual Role Role { get; set; }
}