// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class VehicleInspection
{
    public Guid InspectionId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid StationId { get; set; }

    public Guid StaffId { get; set; }

    public int? BatteryLevel { get; set; }

    public string ConditionNote { get; set; }

    public string ReportType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Staff { get; set; }

    public virtual Station Station { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}