// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class VehicleTransfer
{
    public Guid TransferId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid FromStationId { get; set; }

    public Guid ToStationId { get; set; }

    public Guid StaffId { get; set; }

    public DateTime? TransferDate { get; set; }

    public string Status { get; set; }

    public virtual Station FromStation { get; set; }

    public virtual User Staff { get; set; }

    public virtual Station ToStation { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}