// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Vehicle
{
    public Guid VehicleId { get; set; }

    public Guid StationId { get; set; }

    public string VehicleType { get; set; }

    public int? BatteryCapacity { get; set; }

    public string Status { get; set; }

    public decimal? PricePerHour { get; set; }

    public string LicensePlate { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    public virtual Station Station { get; set; }
}