// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(SWP391RentEVContext))]
    partial class SWP391RentEVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Repository.Models.Blacklist", b =>
                {
                    b.Property<Guid>("BlacklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("BlacklistId")
                        .HasName("PK__Blacklis__AFDBF4182C7461E8");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Blacklist", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Terms")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("ContractId")
                        .HasName("PK__Contract__C90D3469C4705457");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDD6E580CFC0");

                    b.HasIndex("RentalId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Repository.Models.IncidentReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("RentalId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ReportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("ReportId")
                        .HasName("PK__Incident__D5BD4805714850A8");

                    b.HasIndex("RentalId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("IncidentReport", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A383F0D9C78");

                    b.HasIndex("RentalId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Rental", b =>
                {
                    b.Property<Guid>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeliveredByStaffId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeliveryCondition")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PickupStationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReceivedByStaffId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReturnCondition")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReturnStationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("RentalId")
                        .HasName("PK__Rental__97005943384E2FF7");

                    b.HasIndex("ContractId");

                    b.HasIndex("PickupStationId");

                    b.HasIndex("ReturnStationId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rental", (string)null);
                });

            modelBuilder.Entity("Repository.Models.RentalImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ImageId")
                        .HasName("PK__RentalIm__7516F70C713896C0");

                    b.HasIndex("RentalId");

                    b.ToTable("RentalImage", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ReservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("StationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F2483D8858D");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1AF489698B");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Station", b =>
                {
                    b.Property<Guid>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StationId")
                        .HasName("PK__Station__E0D8A6BDE163D1A0");

                    b.ToTable("Station", (string)null);
                });

            modelBuilder.Entity("Repository.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DriverLicense")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdentityCard")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TrustedDeviceExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrustedDeviceHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4CC600D509");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534C6163B8C")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Repository.Models.UserOtp", b =>
                {
                    b.Property<Guid>("UserOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserOtpId")
                        .HasName("PK_UserOtp");

                    b.HasIndex("UserId");

                    b.ToTable("UserOtp", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int?>("BatteryCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("NumberOfRenters")
                        .HasColumnType("int");

                    b.Property<decimal?>("PricePerDay")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<Guid>("StationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Utilities")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__476B54928E3106DE");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Blacklist", b =>
                {
                    b.HasOne("Repository.Models.User", "CreatedByNavigation")
                        .WithMany("BlacklistCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Blacklist__Creat__3493CFA7");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("BlacklistUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Blacklist__UserI__339FAB6E");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.Contract", b =>
                {
                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Contracts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Contract__UserId__5EBF139D");

                    b.HasOne("Repository.Models.Vehicle", "Vehicle")
                        .WithMany("Contracts")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK__Contract__Vehicl__5FB337D6");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Repository.Models.Feedback", b =>
                {
                    b.HasOne("Repository.Models.Rental", "Rental")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RentalId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__Rental__778AC167");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__UserId__76969D2E");

                    b.Navigation("Rental");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.IncidentReport", b =>
                {
                    b.HasOne("Repository.Models.Rental", "Rental")
                        .WithMany("IncidentReports")
                        .HasForeignKey("RentalId")
                        .HasConstraintName("FK__IncidentR__Renta__2BFE89A6");

                    b.HasOne("Repository.Models.User", "Staff")
                        .WithMany("IncidentReportStaffs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__IncidentR__Staff__2EDAF651");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("IncidentReportUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__IncidentR__UserI__2DE6D218");

                    b.HasOne("Repository.Models.Vehicle", "Vehicle")
                        .WithMany("IncidentReports")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK__IncidentR__Vehic__2CF2ADDF");

                    b.Navigation("Rental");

                    b.Navigation("Staff");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Repository.Models.Payment", b =>
                {
                    b.HasOne("Repository.Models.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__RentalI__6FE99F9F");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__UserId__70DDC3D8");

                    b.Navigation("Rental");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.Rental", b =>
                {
                    b.HasOne("Repository.Models.Contract", "Contract")
                        .WithMany("Rentals")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Rental_Contract");

                    b.HasOne("Repository.Models.Station", "PickupStation")
                        .WithMany("RentalPickupStations")
                        .HasForeignKey("PickupStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Rental__PickupSt__68487DD7");

                    b.HasOne("Repository.Models.Station", "ReturnStation")
                        .WithMany("RentalReturnStations")
                        .HasForeignKey("ReturnStationId")
                        .HasConstraintName("FK__Rental__ReturnSt__693CA210");

                    b.HasOne("Repository.Models.User", "Staff")
                        .WithMany("RentalStaffs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Rental__StaffId__6A30C649");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("RentalUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Rental__UserId__66603565");

                    b.HasOne("Repository.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK__Rental__VehicleI__6754599E");

                    b.Navigation("Contract");

                    b.Navigation("PickupStation");

                    b.Navigation("ReturnStation");

                    b.Navigation("Staff");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Repository.Models.RentalImage", b =>
                {
                    b.HasOne("Repository.Models.Rental", "Rental")
                        .WithMany("RentalImages")
                        .HasForeignKey("RentalId")
                        .IsRequired()
                        .HasConstraintName("FK__RentalIma__Renta__17F790F9");

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Repository.Models.Reservation", b =>
                {
                    b.HasOne("Repository.Models.Station", "Station")
                        .WithMany("Reservations")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__Stati__1F98B2C1");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__UserI__1DB06A4F");

                    b.HasOne("Repository.Models.Vehicle", "Vehicle")
                        .WithMany("Reservations")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__Vehic__1EA48E88");

                    b.Navigation("Station");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Repository.Models.User", b =>
                {
                    b.HasOne("Repository.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__4F7CD00D");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repository.Models.UserOtp", b =>
                {
                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("UserOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserOtp_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.Vehicle", b =>
                {
                    b.HasOne("Repository.Models.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK__Vehicle__Station__59063A47");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Repository.Models.Contract", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Repository.Models.Rental", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("IncidentReports");

                    b.Navigation("Payments");

                    b.Navigation("RentalImages");
                });

            modelBuilder.Entity("Repository.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Repository.Models.Station", b =>
                {
                    b.Navigation("RentalPickupStations");

                    b.Navigation("RentalReturnStations");

                    b.Navigation("Reservations");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Repository.Models.User", b =>
                {
                    b.Navigation("BlacklistCreatedByNavigations");

                    b.Navigation("BlacklistUsers");

                    b.Navigation("Contracts");

                    b.Navigation("Feedbacks");

                    b.Navigation("IncidentReportStaffs");

                    b.Navigation("IncidentReportUsers");

                    b.Navigation("Payments");

                    b.Navigation("RentalStaffs");

                    b.Navigation("RentalUsers");

                    b.Navigation("Reservations");

                    b.Navigation("UserOtps");
                });

            modelBuilder.Entity("Repository.Models.Vehicle", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("IncidentReports");

                    b.Navigation("Rentals");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
